In [44]:
try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    pass
else:
    ssl._create_default_https_context = _create_unverified_https_context

In [78]:
import pandas as pd
import numpy as np
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
import ssl
import heapq
import re
pd.options.mode.chained_assignment = None

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/scottcrawshaw/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [46]:
training = pd.read_json('Grocery_and_Gourmet_Food_Reviews_training.json', lines=True)

In [47]:
textOnly = training[['overall', 'reviewText']]

In [48]:
textOnly.dropna();

In [49]:
textOnlyRatings = textOnly['overall']
del textOnly['overall']

In [50]:
# textOnly is a dataframe with only text of review
# textOnlyRatings is a dataframe with only rating of review.
# Each index in textOnly corresponds to the same index in textOnlyRatings

In [59]:
textOnly.values.flatten()

array(["Can't wait to get cooking with these. I have heard about capers and had never tasted them. However aster tasting them I can't wait to get experimenting with some different recipes.",
       'Large and good tasting', 'wonderful', ...,
       "Quinine bitterness not the least bit detectable. In fact not bitter even when drunk straight up.. Overwhelming sourness from all the citric acid. May make a decent albeit pricey whiskey sour. Will neither buy again nor recommend it to anyone. Grocery store tonics are far far better at a small fraction of the price. C'est la vie!",
       "i guess i'm so used to regular tonic, this did not impress me that much, even though it gets great reviews. thought i'd try it at least once.",
       "Maybe this works when added to a drink, but I wanted to use it to make tonic water and the result tasted so bad when I added it to some soda water I made on my Sodastream that I couldn't drink it!  The remainder of the bottle of concentrate went down the dr

In [80]:
dataset = textOnly.values.flatten()[:100] 
for i in range(len(dataset)): 
    dataset[i] = str(dataset[i]).lower() 
    dataset[i] = re.sub(r'\W', ' ', dataset[i]) 
    dataset[i] = re.sub(r'\s+', ' ', dataset[i])

In [76]:
print(dataset)

['can t wait to get cooking with these i have heard about capers and had never tasted them however aster tasting them i can t wait to get experimenting with some different recipes '
 'large and good tasting' 'wonderful' 'capers '
 'these are good quality and cheaper by the use than those tiny bottles that they sell in the stores they are great in tuna sandwiches i like them in potato salad also they came very nicely packaged to prevent breakage i will buy them again '
 'great purchase ' 'fantastic product perfect size and flavor '
 'product as described thank you'
 'not a capers expert but these are delish we always rinse them under cold water in a strainer first before adding to food to wash off excess salt just wish paesana would stop with the neverending price creep or maybe it s not them but amazon '
 'look good'
 'these are so salty that even with repeated changing of the liquid i have trouble with the taste in anything i use them for'
 'these capers are so good i use them very of

In [85]:
word2count = {} 
stop = stopwords.words('english')
for data in dataset: 
    words = nltk.word_tokenize(data) 
    for word in words: 
        if word not in stop:
            if word not in word2count.keys(): 
                word2count[word] = 1
            else: 
                word2count[word] += 1

In [86]:
print(word2count)

{'wait': 3, 'get': 5, 'cooking': 2, 'heard': 1, 'capers': 8, 'never': 1, 'tasted': 3, 'however': 3, 'aster': 1, 'tasting': 7, 'experimenting': 1, 'different': 1, 'recipes': 3, 'large': 4, 'good': 29, 'wonderful': 3, 'quality': 8, 'cheaper': 1, 'use': 26, 'tiny': 1, 'bottles': 1, 'sell': 1, 'stores': 2, 'great': 32, 'tuna': 2, 'sandwiches': 1, 'like': 8, 'potato': 2, 'salad': 4, 'also': 4, 'came': 1, 'nicely': 1, 'packaged': 2, 'prevent': 1, 'breakage': 1, 'buy': 9, 'purchase': 7, 'fantastic': 2, 'product': 12, 'perfect': 5, 'size': 4, 'flavor': 3, 'described': 2, 'thank': 3, 'expert': 1, 'delish': 1, 'always': 2, 'rinse': 1, 'cold': 1, 'water': 2, 'strainer': 1, 'first': 5, 'adding': 2, 'food': 2, 'wash': 2, 'excess': 1, 'salt': 5, 'wish': 1, 'paesana': 1, 'would': 5, 'stop': 1, 'neverending': 1, 'price': 15, 'creep': 1, 'maybe': 1, 'amazon': 6, 'look': 2, 'salty': 5, 'even': 3, 'repeated': 1, 'changing': 1, 'liquid': 1, 'trouble': 1, 'taste': 11, 'anything': 3, 'often': 1, 'couscous':

In [87]:
freq_words = heapq.nlargest(100, word2count, key=word2count.get)
# 100 says that we should only pay attention to the top 100 most frequent words. Change as youd like

In [88]:
X = [] 
for data in dataset: 
    vector = [] 
    for word in freq_words: 
        if word in nltk.word_tokenize(data): 
            vector.append(1) 
        else: 
            vector.append(0) 
    X.append(vector) 
X = np.asarray(X) 

In [96]:
print(X)

[[0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [1 0 0 ... 0 0 0]
 [1 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
